name: build and deploy gestion produits

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker php image
        run: docker build ./php -t 20220796/php-renf-eval:${{ vars.APP_VERSION }} -t 20220796/php-renf-eval:${{ github.sha }}

      - name: Build Docker mysql image
        run: docker build ./database -t 20220796/mysql-renf-eval:${{ vars.APP_VERSION }} -t 20220796/mysql-renf-eval:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker php image
        run: |
          docker push 20220796/php-renf-eval:${{ vars.APP_VERSION }}
          docker push 20220796/php-renf-eval:${{ github.sha }}

      - name: Push Docker mysql image
        run: |
          docker push 20220796/mysql-renf-eval:${{ vars.APP_VERSION }}
          docker push 20220796/mysql-renf-eval:${{ github.sha }}

  deploy-kube:
    runs-on: ubuntu-latest
    needs: [build-publish]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set kubeconfig
        run: |
          mkdir -p ~/.kube
          printf "%s" "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster access
        run: kubectl cluster-info

      - name: Deploy manifests
        run: |
          cd k8s
          kubectl apply -n maimiti -f .
